name: Build and test gazer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Update apt
      run: sudo apt-get update
    - name: Set up dependencies
      run: sudo apt-get install -y build-essential cmake wget lsb-release software-properties-common zlib1g-dev openjdk-11-jre python3 python3-pip python3-setuptools python3-psutil
    - name: Set up some more dependencies
      run: |
        sudo apt-get install -y clang-11 llvm-11-dev llvm-11-tools llvm-11-runtime libboost-all-dev
        sudo ln -sf /usr/bin/clang-11 /usr/bin/clang
        sudo ln -s `which opt-11` /usr/bin/opt -f
        sudo ln -s `which FileCheck-11` /usr/bin/FileCheck
        sudo pip3 install lit
    - name: Set up portfolio dependencies
      run: sudo apt-get install -y perl libyaml-tiny-perl libproc-processtable-perl
    - name: Build
      run: cmake -DCMAKE_CXX_COMPILER=clang++-9 -DGAZER_ENABLE_UNIT_TESTS=On -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=On . && make
    - name: Get Theta
      run: |
        mkdir tools/gazer-theta/theta
        mkdir tools/gazer-theta/theta/lib
        wget "https://github.com/ftsrg/theta/releases/download/$THETA_VERSION/theta-cfa-cli.jar" -O tools/gazer-theta/theta/theta-cfa-cli.jar
        wget "https://github.com/ftsrg/theta/raw/$THETA_VERSION/lib/libz3.so" -P tools/gazer-theta/theta/lib/
        wget "https://github.com/ftsrg/theta/raw/$THETA_VERSION/lib/libz3java.so" -P tools/gazer-theta/theta/lib/
      env:
        THETA_VERSION: v2.10.0
    - name: Run unit tests
      run: make check-unit
    - name: Run functional tests
      run: make check-functional
